controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# config/routes.yaml
dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

home:
    path: /acceuil
    controller: App\Controller\HomeController::index

# config/routes.yaml
home_login:
    path: /home/login
    controller: App\Controller\HomeController::login

# config/routes.yaml
home_account:
    path: /home/account
    controller: App\Controller\HomeController::account

home_appartement:
    path: /home/appartements
    controller: App\Controller\AppartementController::index2

